version: '3'

services:
    zookeeper:
      image: confluentinc/cp-zookeeper:5.4.0
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000

    kafka:
        image: confluentinc/cp-kafka:5.4.0
        depends_on:
          - zookeeper
        environment:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
          KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_NUM_PARTITIONS: 37
        ports:
          - "0.0.0.0:9092:9092"
          - "0.0.0.0:9093:9093"

        volumes:
          - ./dataset.txt:/tmp/dataset.txt:ro
          - ./inject_dataset.sh:/tmp/inject_dataset.sh:ro

    kafka-rest-proxy:
        image: confluentinc/cp-kafka-rest
        depends_on:
          - kafka
        environment:
          KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_REST_LISTENERS: http://kafka-rest-proxy:8082
          KAFKA_REST_HOST_NAME: kafka-rest-proxy
          KAFKA_REST_BOOTSTRAP_SERVERS: kafka:29092
        ports:
          - "0.0.0.0:8082:8082"

    kafka-create-topics:
        image: confluentinc/cp-kafka:5.4.0
        depends_on:
          - kafka
        command: "bash -c 'echo Waiting for Kafka to be ready... && \
                           cub kafka-ready -b kafka:29092 1 20 && \
                           kafka-topics --create --topic bench1_feature --if-not-exists --zookeeper zookeeper:2181 --partitions 37 --replication-factor 1 && \
                           kafka-topics --create --topic bench1_makinage --if-not-exists --zookeeper zookeeper:2181 --partitions 37 --replication-factor 1 && \
                           sleep infinity'"
        environment:
          KAFKA_BROKER_ID: ignored
          KAFKA_ZOOKEEPER_CONNECT: ignored

    makinage-benchmark:
        image: makinage-benchmark:latest
        depends_on:
          - kafka
          - kafka-create-topics
        command: makinage --config /opt/makinage/config.yaml
